"""empty message

Revision ID: b8353abfcc6d
Revises: 
Create Date: 2018-08-20 23:20:28.084766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8353abfcc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_author', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comment_text', sa.UnicodeText(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.drop_table('Tag')
    op.drop_table('Post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Post_id_seq"\'::regclass)'), nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('file', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Post_pkey'),
    sa.UniqueConstraint('file', name='Post_file_key'),
    sa.UniqueConstraint('image', name='Post_image_key'),
    sa.UniqueConstraint('title', name='Post_title_key'),
    sa.UniqueConstraint('url', name='Post_url_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Tag',
    sa.Column('tag_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tag_tag_id_seq"\'::regclass)'), nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_title', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], name='Tag_post_id_fkey'),
    sa.PrimaryKeyConstraint('tag_id', name='Tag_pkey')
    )
    op.drop_table('comment')
    # ### end Alembic commands ###
